### ISSUE TITLE
Genymotion web testing support broken as of release 1.7-p1

### ISSUE THREAD

**Issue by bonigarcia** [budtmo/docker-android#158]
**Operating System**
Ubuntu 18.04.2 LTS

**Docker Image**
`budtmo/docker-android-genymotion:1.7-p0`, `budtmo/docker-android-genymotion:1.7-p1`, and `budtmo/docker-android-genymotion:1.8-p0`

**Docker Version**
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Docker Command to start docker-android**
Executed from a Java client with the following configuration:

- Envs:
  - `[DEVICE=SamsungS7V6, SCREEN_WIDTH=1900, SCREEN_HEIGHT=900, SCREEN_DEPTH=24+32, APPIUM=true, AUTO_RECORD=false, TYPE=SaaS, USER=my-user, PASS=my-pass, LICENSE=my-license-key]`
- Cmd:
  - `[sh, -c, mkdir /root/tmp; echo '[{"template":"Samsung Galaxy S7 - 6.0.0 - API 23 - 1440x2560","device":"SamsungS7V6"}]' > /root/tmp/devices.json; wget https://chromedriver.storage.googleapis.com/2.18/chromedriver_linux64.zip; unzip chromedriver_linux64.zip; cp chromedriver /usr/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64; rm chromedriver*; ./geny_start.sh]`
- Port binding:
  - `0.0.0.0:32931->4723/tcp`

Notice that I override the cmd in order to download the proper chromedriver version (2.18 in this case) to be able to control the Chrome browser within the Android device properly from a Selenium test.

## Expected Behavior
I want to run a Selenium test using the following parameters:
- Hub URL: http://172.17.0.1:32931/wd/hub
- Capabilities: `{browserName: chrome, deviceName: SamsungS7V6}`

During the execution of the test, the automated use of Chrome in the Android device can be seen in the Genymotion cloud (https://cloud.geny.io/). Of course it is a pre-requisite having an account. The credentials values are passed as envs in the container config: `USER=my-user, PASS=my-pass, LICENSE=my-license-key`.

## Actual Behavior
Everything works fine using `budtmo/docker-android-genymotion:1.7-p0`. I have an automated [test](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/android/AndroidGenymotionJupiterTest.java) in my project Selenium-Jupiter (Java). Unfortunately this test is broken when using `budtmo/docker-android-genymotion:1.7-p1` and `budtmo/docker-android-genymotion:1.8-p0`. I suppose the problem is related with the Appium Server version, which is the change from 1.7-p0 to 1.7-p1.

Any idea?

**Comment by budtmo** [comment]
Hi @bonigarcia , 

I will replace the old gmtool with gmsaas anyway. I will keep you updated so you can try it out.

**Comment by budtmo** [comment]
Hi @bonigarcia , 

I just released version [1.8-p2](https://github.com/budtmo/docker-android/releases/tag/1.8-p2) which replaced gmtool with gmsaas. It would be great if you can retry again and give a feedback.

**Comment by bonigarcia** [comment]
I have just made the same test but using `budtmo/docker-android-genymotion:1.8-p2` and the issue remains with this new version. The latest working version is still `budtmo/docker-android-genymotion:1.7-p0`.

**Comment by budtmo** [comment]
@lilinor could you help me with this one? I have no clue what I miss here :/
